# Generated by Django 3.1.5 on 2021-01-20 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('link', models.URLField(null=True)),
                ('description', models.TextField(null=True)),
                ('type_space', models.BooleanField(default=True, verbose_name='Space news source')),
                ('logo', models.URLField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(default='', null=True)),
                ('link', models.URLField(default='', unique=True)),
                ('image', models.URLField(null=True)),
                ('published', models.DateTimeField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.source')),
            ],
            options={
                'ordering': ['-published'],
            },
        ),
    ]
