# Generated by Django 3.1.5 on 2021-02-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='name',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
